[project]
name = "backend"
version = "0.1.0"
description = "FastAPI Backend mit SQLite Datenbank"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
]

[project.scripts]
backend = "main:main"
